from app.tag import tag_router
from app.chat import chat_router
from app.comment import comment_router
from app.article import article_router
from app.donation import donation_router
from app.category import category_router
from app.visit_log import visit_log_router
from app.friend_link import friend_link_router
from app.monthes import monthes_router
from app.finance import finance_router
from app.terminus import terminus_router